### ISSUE TITLE
Replace all OS specific path references with python functions

### ISSUE THREAD

**Issue by nwmoriarty** [kimdn/cryo_fit#1]
Replace mkdir with os.mkdir()
Replace "path1/path2" with os.path.join()
Etc... ⬆️

**Comment by kimdn** [comment]
ok Nigel. I will change these. thanks

**Comment by kimdn** [comment]
@nwmoriarty  
Thank you Nigel, thanks to you, my python skill is improved more.
I believe that I changed all mkdir to os.mkdir().

However, I didn't do 
Replace "path1/path2" with os.path.join()
for this phase I, because as I explained to you @skirmizi Serdal wants to all input, output files, running py codes in each folder independently.

As we talked before, let's pursue this cleaner method of programming in phase 2.
Although I close this issue, you may reopen of course.
